language: node_js
os: linux
node_js:
  - "6"
before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
install:
  - npm install -g grunt-cli
  - npm install -g coveralls
  - npm install -g codecov
  - npm install
script:
  - grunt test
  - npm test
after_success:
  - npm run coverage
  - npm run clean